// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOQd2Vlnx8F7NC3AJabcVvMC7yNwCrqo',
    appId: '1:788128692183:web:1593d30fa8bb7efe9c3d92',
    messagingSenderId: '788128692183',
    projectId: 'fir-shopper-cebc5',
    authDomain: 'fir-shopper-cebc5.firebaseapp.com',
    databaseURL: 'https://fir-shopper-cebc5.firebaseio.com',
    storageBucket: 'fir-shopper-cebc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwAJJgqXjduj48qi7U791ISGw7VaQ6C1Q',
    appId: '1:788128692183:android:209fb0a283ea83269c3d92',
    messagingSenderId: '788128692183',
    projectId: 'fir-shopper-cebc5',
    databaseURL: 'https://fir-shopper-cebc5.firebaseio.com',
    storageBucket: 'fir-shopper-cebc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV3flNXq84wRsvWn3IbFV86rKWyWNTdH8',
    appId: '1:788128692183:ios:018126965b343f489c3d92',
    messagingSenderId: '788128692183',
    projectId: 'fir-shopper-cebc5',
    databaseURL: 'https://fir-shopper-cebc5.firebaseio.com',
    storageBucket: 'fir-shopper-cebc5.appspot.com',
    iosClientId: '788128692183-5c19utp4op3au8sjrjml2fu7trsj5jck.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryApp',
  );
}
